### PR TITLE
Redirect all output to debug stream in debug mode

### LINKED ISSUE #97: debug mode should not mute output
Debug mode shouldn't mute the output, especially stderr. Usually when I get things wrong, it's because some traceback is raised (e.g., an AttributeError in the parsed_args argument of the completer). 

I tried disabling the muting in debug mode, but it didn't work. I'm not sure what I was doing wrong.

### PR DESCRIPTION
**Pull request by evanunderscore**
Fixes #97

### CODE REVIEW

File: argcomplete/bash_completion.d/python-argcomplete.sh [hunk 1]
```diff
@@ -12,6 +12,17 @@ __python_argcomplete_expand_tilde_by_ref () {
...
 
+# Run something, muting output or redirecting it to the debug stream
+# depending on the value of _ARC_DEBUG.
+__python_argcomplete_run() {
+    if [[ -z "$_ARC_DEBUG" ]]; then
+        "$@" 8>&1 9>&2 1>/dev/null 2>&1
+    else
+        "$@" 8>&1 9>&2 1>&9 2>&1
+    fi
+    return $?
```
Comment (kislyuk) [inline argcomplete/bash_completion.d/python-argcomplete.sh]: Doesn't this happen by default?

Comment (evanunderscore) [inline argcomplete/bash_completion.d/python-argcomplete.sh]: I wasn't aware of that. Thanks.
